<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CotizacionPrenda extends Model
{
    use HasFactory;
    protected $table ='cotizaciones_prendas';
    protected $primaryKey ='id_cotizacionprenda';
    protected $fillable =[
        'nombre_prenda',
        'descripcion_generica',
        'valor_oro_plata',
        'dato_1',
        'dato_2',
        'dato_3',
        'dato_4',
        'promedio_prenda',
        'kilataje_prenda',
        'gramaje_prenda',
        'caracteristicas_prenda',
        'avaluo_prenda',
        'porcentaje_prestamo_sobre_avaluo',
        'prestamo_prenda',
        'cantidad_prenda',  

        'nombre_prenda_2',
        'descripcion_generica_2',
        'dato_1_2',
        'dato_2_2',
        'dato_3_2',
        'dato_4_2',
        'promedio_prenda_2',
        'kilataje_prenda_2',
        'gramaje_prenda_2',
        'caracteristicas_prenda_2',
        'avaluo_prenda_2',
        'porcentaje_prestamo_sobre_avaluo_2',
        'prestamo_prenda_2',
        'cantidad_prenda_2',

        'nombre_prenda_3',
        'descripcion_generica_3',
        'dato_1_3',
        'dato_2_3',
        'dato_3_3',
        'dato_4_3',
        'promedio_prenda_3',
        'kilataje_prenda_3',
        'gramaje_prenda_3',
        'caracteristicas_prenda_3',
        'avaluo_prenda_3',
        'porcentaje_prestamo_sobre_avaluo_3',
        'prestamo_prenda_3',
        'cantidad_prenda_3',
   
        'nombre_prenda_4',
        'descripcion_generica_4',
        'dato_1_4',
        'dato_2_4',
        'dato_3_4',
        'dato_4_4',
        'promedio_prenda_4',
        'kilataje_prenda_4',
        'gramaje_prenda_4',
        'caracteristicas_prenda_4',
        'avaluo_prenda_4',
        'porcentaje_prestamo_sobre_avaluo_4',
        'prestamo_prenda_4',
        'cantidad_prenda_4',

        'nombre_prenda_5',
        'descripcion_generica_5',
        'dato_1_5',
        'dato_2_5',
        'dato_3_5',
        'dato_4_5',
        'promedio_prenda_5',
        'kilataje_prenda_5',
        'gramaje_prenda_5',
        'caracteristicas_prenda_5',
        'avaluo_prenda_5',
        'porcentaje_prestamo_sobre_avaluo_5',
        'prestamo_prenda_5',
        'cantidad_prenda_5',

        'nombre_prenda_6',
        'descripcion_generica_6',
        'dato_1_6',
        'dato_2_6',
        'dato_3_6',
        'dato_4_6',
        'promedio_prenda_6',
        'kilataje_prenda_6',
        'gramaje_prenda_6',
        'caracteristicas_prenda_6',
        'avaluo_prenda_6',
        'porcentaje_prestamo_sobre_avaluo_6',
        'prestamo_prenda_6',
        'cantidad_prenda_6',
        'prestamo_ava',
        'prestamo_por',
        'prestamo_lote',
        'lote',
    ];
}
